/* m-sequence generated by polynomial x^6 + X^5 + 1, started in the 100000
 * state and augmented with an extra 0 at the front to make a 64-bit sequence
 * 0000 0010  0001 1000  1010 0111  1010 0011
 * 1001 0010  1101 1101  1001 1010  1011 1111
 */
#define SYNC1	0x0218a7a3L
#define	SYNC2	0x92dd9abfL

